### ISSUE TITLE
Demo Doesn't Work on HTTPS Connections

### ISSUE THREAD

**Issue by jsharkey13** [daviesian/equality#1]
The demo version here:

https://daviesian.github.io/equality/resources/public/index.html

doesn't work because the [two JS files here](https://github.com/daviesian/equality/blob/master/src/equality/handler.clj#L24-L25) are loaded over HTTP and blocked.

**Comment by daviesian** [comment]
Actually it's [these two lines](https://github.com/daviesian/equality/blob/master/resources/public/js/app.js#L10-L11), but now fixed anyway.
